"use client";

import { BookMarked, Plus, RotateCcw, X } from "lucide-react";
import { useState, type FormEvent } from "react";
import type { MistakeItem } from "./types";

export interface MistakeBookProps {
  mistakes: MistakeItem[];
  subjectOptions?: string[];
  onCreate?: (mistake: Omit<MistakeItem, "id">) => void;
  onReview?: (mistake: MistakeItem) => void;
}

export function MistakeBook({ mistakes, subjectOptions = [], onCreate, onReview }: MistakeBookProps) {
  const [isComposerOpen, setIsComposerOpen] = useState(false);
  const [draft, setDraft] = useState({ concept: "", subject: subjectOptions[0] ?? "", source: "", reason: "", correction: "", nextReviewLabel: "Tomorrow" });
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!draft.concept.trim() || !draft.correction.trim()) return; onCreate?.(draft); setDraft({ concept: "", subject: subjectOptions[0] ?? "", source: "", reason: "", correction: "", nextReviewLabel: "Tomorrow" }); setIsComposerOpen(false); };
  return <section className="workspace-page mistake-book" aria-labelledby="mistake-book-title"><header className="workspace-page-header"><div><p className="workspace-eyebrow"><BookMarked aria-hidden="true" /> Mistake book</p><h1 id="mistake-book-title">Turn every wrong answer into a future advantage.</h1><p>Keep the correction and the reason the error happened together.</p></div><button className="workspace-primary-button" type="button" onClick={() => setIsComposerOpen(true)}><Plus aria-hidden="true" /> Add a mistake</button></header>{isComposerOpen ? <form className="workspace-composer grid gap-6" onSubmit={submit}><div className="workspace-composer-header"><h2>Capture the learning</h2><button className="workspace-icon-button" type="button" aria-label="Close mistake form" onClick={() => setIsComposerOpen(false)}><X aria-hidden="true" /></button></div><label>Concept<input required value={draft.concept} onChange={(event) => setDraft({ ...draft, concept: event.target.value })} placeholder="For example, page replacement" /></label><div className="grid gap-6 sm:grid-cols-2"><label>Subject<select value={draft.subject} onChange={(event) => setDraft({ ...draft, subject: event.target.value })}><option value="">Choose a subject</option>{subjectOptions.map((subject) => <option key={subject}>{subject}</option>)}</select></label><label>Question source<input value={draft.source} onChange={(event) => setDraft({ ...draft, source: event.target.value })} placeholder="Mock test, textbook, or notes" /></label></div><label>Why did this go wrong?<textarea value={draft.reason} onChange={(event) => setDraft({ ...draft, reason: event.target.value })} rows={3} /></label><label>Correct reasoning<textarea required value={draft.correction} onChange={(event) => setDraft({ ...draft, correction: event.target.value })} rows={4} /></label><button className="workspace-primary-button" type="submit">Save to mistake book</button></form> : null}<div className="mistake-book-list">{mistakes.map((mistake) => <article className="mistake-card" key={mistake.id}><div className="mistake-card-heading"><div className="min-w-0"><span className="workspace-chip">{mistake.subject}</span><h2 className="mt-2 break-words">{mistake.concept}</h2><p className="mt-1 break-words text-[var(--muted)]" style={{ fontSize: "var(--text-sm)" }}>{mistake.source}</p></div><button className="workspace-secondary-button shrink-0" type="button" onClick={() => onReview?.(mistake)}><RotateCcw aria-hidden="true" /> Review {mistake.nextReviewLabel}</button></div><dl><div><dt>Why it happened</dt><dd className="max-w-[65ch] break-words">{mistake.reason}</dd></div><div><dt>Correct reasoning</dt><dd className="max-w-[65ch] break-words">{mistake.correction}</dd></div></dl></article>)}</div>{!mistakes.length ? <p className="workspace-empty-state"><span className="block max-w-[38ch]">Your mistakes are not a record of failure. They are a map for the next revision.</span></p> : null}</section>;
}
