"use client";

import { CalendarClock, Check, Filter, RotateCcw } from "lucide-react";
import { useMemo, useState } from "react";
import type { RevisionItem } from "./types";

export interface RevisionWorkspaceProps {
  items: RevisionItem[];
  onComplete?: (item: RevisionItem) => void;
  onReschedule?: (item: RevisionItem) => void;
}

export function RevisionWorkspace({ items, onComplete, onReschedule }: RevisionWorkspaceProps) {
  const [filter, setFilter] = useState<"all" | "due" | "topic" | "note" | "mistake">("all");
  const visibleItems = useMemo(() => items.filter((item) => filter === "all" || (filter === "due" ? !item.completed : item.source === filter)), [filter, items]);
  return <section className="workspace-page revision-workspace" aria-labelledby="revision-workspace-title"><header className="workspace-page-header"><div><p className="workspace-eyebrow"><CalendarClock aria-hidden="true" /> Revision queue</p><h1 id="revision-workspace-title">Give important ideas another meeting.</h1><p>Reviews stay deliberate, with the reason you saved them attached.</p></div></header><div className="workspace-filter-bar flex-wrap items-center" aria-label="Filter revision items"><Filter aria-hidden="true" size={16} className="shrink-0 text-[var(--muted)]" />{(["all", "due", "topic", "note", "mistake"] as const).map((option) => { const isSelected = filter === option; return <button className={`workspace-filter-button${isSelected ? " is-selected" : ""} inline-flex min-h-11 shrink-0 items-center justify-center rounded-full border px-4 text-[0.82rem] font-bold transition-colors ${isSelected ? "border-[var(--accent)] bg-[var(--soft-accent)] text-[var(--accent)]" : "border-[var(--line)] bg-[var(--surface)] text-[var(--ink)] hover:border-[var(--accent)]"}`} key={option} type="button" aria-pressed={isSelected} onClick={() => setFilter(option)}>{option === "due" ? "Due now" : option[0].toUpperCase() + option.slice(1)}</button>; })}</div><ol className="revision-item-list">{visibleItems.map((item) => <li className={item.completed ? "is-complete" : ""} key={item.id}><article className={`flex flex-col gap-4 rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow)] sm:flex-row sm:items-center sm:justify-between sm:p-6${item.completed ? " opacity-70" : ""}`}><div className="min-w-0"><span className="workspace-chip">{item.source ?? "topic"}</span><h2 className="mt-2 break-words font-normal leading-snug" style={{ fontFamily: "var(--font-display)", fontSize: "var(--text-xl)" }}>{item.title}</h2><p className="mt-1 break-words text-[var(--muted)]">{item.subject} · {item.dueLabel}</p></div><div className="workspace-row-actions sm:shrink-0">{item.completed ? <span className="workspace-complete-label inline-flex min-h-11 items-center gap-2 rounded-full bg-[var(--soft-accent)] px-4 text-[0.82rem] font-bold text-[var(--accent)]"><Check aria-hidden="true" size={16} /> Reviewed</span> : <button className="workspace-primary-button" type="button" onClick={() => onComplete?.(item)}><Check aria-hidden="true" /> Mark reviewed</button>}<button className="workspace-icon-button shrink-0" type="button" aria-label={`Reschedule ${item.title}`} onClick={() => onReschedule?.(item)}><RotateCcw aria-hidden="true" /></button></div></article></li>)}</ol>{!visibleItems.length ? <p className="workspace-empty-state"><span className="block max-w-[38ch]">Nothing here yet. The topics you want to keep will come back at the right time.</span></p> : null}</section>;
}
