"use client";

import { ArrowUpRight, Check, Copy, Send } from "lucide-react";
import { useMemo, useState } from "react";

export function HandoffDesk() {
  const [subject, setSubject] = useState("");
  const [topic, setTopic] = useState("");
  const [understanding, setUnderstanding] = useState("");
  const [question, setQuestion] = useState("");
  const [copied, setCopied] = useState(false);
  const context = useMemo(() => `I am preparing for GATE CS/IT 2027.\nSubject: ${subject || "Not selected"}\nTopic: ${topic || "Not selected"}\nWhat I currently understand:\n${understanding || "I have not written this yet."}\n\nHelp me with this specific task:\n${question || "Ask me questions that reveal gaps in my understanding. Do not immediately give the answer."}\n\nKeep the explanation aligned to GATE-level depth. Use active recall and point out any incorrect assumptions.`, [question, subject, topic, understanding]);
  async function copy() { await navigator.clipboard.writeText(context); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }
  return <section className="workspace-page" aria-labelledby="handoff-title"><header className="workspace-page-header"><div><p className="workspace-eyebrow"><Send aria-hidden="true" /> AI handoff</p><h1 id="handoff-title">Carry the right context with you.</h1><p>GATE OS prepares a focused prompt. You choose where to continue; your private files never leave automatically.</p></div></header><div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><form className="workspace-panel grid gap-4"><label className="field-label">Subject<input className="text-field" value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="Operating Systems" /></label><label className="field-label">Topic<input className="text-field" value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="Deadlocks" /></label><label className="field-label">What you understand<textarea className="textarea-field" rows={5} value={understanding} onChange={(event) => setUnderstanding(event.target.value)} placeholder="Explain it in your own words first." /></label><label className="field-label">What help you want<textarea className="textarea-field" rows={4} value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Test me with one conceptual question at a time." /></label></form><section className="workspace-panel flex flex-col"><div><p className="workspace-eyebrow">Prepared context</p><h2 className="mt-2">Review before sending</h2></div><pre className="mt-5 flex-1 whitespace-pre-wrap rounded-2xl bg-[var(--background)] p-5 font-mono text-xs leading-6 text-[var(--muted)]">{context}</pre><div className="mt-5 flex flex-wrap gap-2"><button className="workspace-primary-button" type="button" onClick={copy}>{copied ? <Check size={16} /> : <Copy size={16} />}{copied ? "Copied" : "Copy context"}</button><a className="workspace-secondary-button" href="https://chatgpt.com/" target="_blank" rel="noreferrer">Open ChatGPT <ArrowUpRight size={16} /></a><a className="workspace-secondary-button" href="https://notebooklm.google.com/" target="_blank" rel="noreferrer">Open NotebookLM <ArrowUpRight size={16} /></a></div><p className="workspace-field-help mt-4">GATE OS does not send prompts, notes, or PDFs to third-party AI services. You stay in control of the handoff.</p></section></div></section>;
}
